fix remove derive(Versionize) of FsOptions
due to compile error above the 1.46+ of rustc
```
error: proc-macro derive panicked
   --> src/abi/linux_abi.rs:172:38
    |
172 |     #[derive(Deserialize, Serialize, Versionize)]
    |                                      ^^^^^^^^^^
    |
    = help: message: Unsupported field type Group(TypeGroup { group_token: Group, elem: Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "u32", span: #158 bytes(7173779..7173781) }, arguments: None }] } }) })
```
please use VfsOptionsState to support snapshot/live-upgrade in
src/api/vfs_persist.rs:35, it is used to impl Persist for VfsOptions.

Signed-off-by: wanglei01 <wanglei01@alibaba-inc.com>