api: fix fuse init-msg response overflow
Under kenrel fuse version 7.23, init-msg response has a smaller
size than those >= 7.23. So we have to struncate `out` memory buffer
before converting it a value of ByteValued.

Otherwise, nydusd will panic.

iout_opts: ASYNC_READ | ATOMIC_O_TRUNC | BIG_WRITES | AUTO_INVAL_DATA | DO_READDIRPLUS | READDIRPLUS_AUTO | ASYNC_DIO
thread 'fuse_server' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/git/checkouts/fuse-backend-rs-8dd7d4d429d69b6e/d96379d/src/api/server/sync_io.rs:725:34
stack backtrace:
   0: rust_begin_unwind
       at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
       at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
       at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: fuse_rs::api::server::sync_io::<impl fuse_rs::api::server::Server<F>>::handle_message

Signed-off-by: Changwei Ge <chge@linux.alibaba.com>