fix compile error, 1.46+ of rustc
```
error: proc-macro derive panicked
   --> libs/fuse-backend-rs/src/abi/linux_abi.rs:172:14
    |
172 |     #[derive(Versionize)]
    |              ^^^^^^^^^^
    |
    = help: message: Unsupported field type Group(TypeGroup { group_token: Group, elem: Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "u32", span: #158 bytes(7170701..7170703) }, arguments: None }] } }) })
```
we need to implement save and restore manually

Signed-off-by: wanglei01 <wanglei01@alibaba-inc.com>