build: fix a build failure related to conditional compilation
Fix a build failure related to conditional compilation:
error[E0063]: missing field `id_mapping` in initializer of `VfsOptions`
   --> src/api/vfs/mod.rs:751:16
    |
751 |             Ok(VfsOptions {
    |                ^^^^^^^^^^ missing `id_mapping`

Signed-off-by: Jiang Liu <gerry@linux.alibaba.com>